### ISSUE TITLE
Center Block Tag not working on small screen sizes in IE11

### ISSUE THREAD

**Issue by crystalrubik** [cdig/cd-module#13]
`<center-block>` when in IE11 at a small screen size (smaller than the width of the sentence), it moves to the very left edge, with no padding. 

IE11, Windows 7
Trican Acid Project, Das Scada & Sensors Module, Adjusting the K-factor Slide.

**Comment by ivyreese** [comment]
It might be better to just live with this. While it is possible to work around this bug, doing it in all the places that it crops up is really bad from a complexity standpoint, and it's the sort of issue that should be pretty rarely seen.

The underlying issue is how flex box handles intrinsic sizes. It might be better to just focus on making the behavior as good as possible in the browsers that get the implementation right, and only worrying about major breaking bugs in IE at that narrow size.

**Comment by ivyreese** [comment]
Actually, extrinsic sizes are pretty screwed up too. But Flexbox is really the only half-decent layout tool at this point, so we sort of have to use it, edge cases be damned.

**Comment by crystalrubik** [comment]
I agree, it's not a huge deal and should really never be seen. Just reporting what I see.

**Comment by ivyreese** [comment]
Yes! Thank you, and please continue to report stuff like this here. Sean and I can add our notes about "what and why", and then as we get time, we can review the notes, review the issues, and see what we can do to make it better.

Also, thanks for listing an example module & page to see the error. This really helps. In the future, you'll even be able to attach a specific version of your page, so that if you change it (say, to work around the error), we can still see the exact error you were facing. But we won't get that set up until I get back.

**Comment by ivyreese** [comment]
This is being fixed in v2 be revisiting all the primitives and removing smartphone support.
