### ISSUE TITLE
Pins over flash don't stick nicely in place 

### ISSUE THREAD

**Issue by crystalrubik** [cdig/cd-module#17]
`<cd-map>` pins over flash move way off their position when shrinking the width of the browser. Seems to happen a lot at first and then decides to stick in place after a bit. Like around the width of 1160px it starts to move, then stops and sticks at around 1024px wide. 

Examples:
Process Control Valves, Activity: the word Start is a pin. 
Bowie Pump, Positive Vs. Non-Positive: This one has a lot of labels, and a lot of break points, and it works ok. But at first the Add button label goes over the button then jumps up again after a bit. 

Just reporting this and also wondering if it's anything to really worry about?

Trican Acid Project
Chrome on Mac, IE on Windows 7 (and possible more browsers)

**Comment by ivyreese** [comment]
I'm not at a computer now, and won't be for a few days, so forgive me for asking questions I could otherwise answer by checking it myself.

Are the problematic pinned items always text? Or are there images that also exhibit this issue when placed atop flash?

Are the pinned items assigned a reasonable anchor point, like `pin="center"`?

Are you keeping in mind the fact that text doesn't scale? If you need the text to scale with the SWF, as though it were an image with a % width, you will probably need to put the text in an SVG and pin the SVG over the flash content. This will work in theory, but may cause other issues. This is an area where we need to do further research into the best approach.

**Comment by crystalrubik** [comment]
I just tested images and an svg as well, they seem to have the same issue as text. I can use `pin="bottom"` and it will shift down for the first bit and then stick in place. (ex. in Pressure Relief Valves module, How Does a PRV Work?). 

In the Pressure Relief Valves module, I can get most swfs with text behaving except one.

Examples of working pages:
-Fluidic Principles
-Activity
-Identify the Pressure 
-Set Pressure

Example of page not working:
How Does a PRV Work?

They do seem to need the pin defined to work well, ex `pin="bottom center"`.

I can't find any differences that makes that swf any different from the others. Some seem to have this problem and others don't so much. 

I realize text doesn't scale, so no that's not the issue.

**Comment by ivyreese** [comment]
So, the issue is that the stage size of the SWF doesn't match the size of the space it's occupying in the page. The SWF is too tall, and the space is too wide. So the SWF stretches, and fills the left and right sides with whitespace**. This doesn't match the way that images scale, so cd-map can't deal with it very well.

To fix this issue with cd-map `pin` elements not staying in the correct position visually, you need to exert a bit of extra control over the width of the cd-map or the height of the cd-swf, so that they don't leave any extra _width_ for the SWF to fill with whitespace. There are a bunch of ways to do this, but here are 2 easy ones:
1. Set a max-width on the cd-map that suits the size of the SWF. By default, cd-swf sets the height of SWFs to 540px**, so if the SWF has the default stage size of 960x540, you can set `max-width:960px;` on the cd-map, and you're good. You might want to also set `margin: 0 auto;` on the cd-map to keep it in the centre.
2. Increase the height of the cd-swf until it fills the width, and begins to stretch in the height and make whitespace on the top and bottom. This method is a little riskier than the first one, because if we ever increase the maximum width of pages, this will break. But, it might be the right method to use for SWFs that aren't 960x540. Anyway, what you do is set the height of the cd-swf to something big like `height: 800px;`, then look at how much whitespace there is at the top and bottom, and then gradually nudge down the height until it is just about to start shrinking the width, but not quite. In the PRV example, I found that `height: 600px` worked nicely.

If you do these things, then the scaling should work perfectly.

One last thing to note: you must set the width on the pinned elements that you'd like to have scale, and that width must be a percentage. In the PRV example, the "SVG TEXT" had `height: 1em`, which won't scale properly. You don't need to set the width if the text isn't supposed to scale, however. But if you're putting text inside an SVG to get nice scaling behaviour (which is a temporary hack until we figure out a better method for doing scaling text in a cd-map), just remember to set a width %.

🍰

**SWFs are stupid and have an intrinsic size different than their stage size, so I have to manually specify a size in cd-swf ([here's the line of code that does this](https://github.com/cdig/cd-module/blob/master/dist/components/cd-swf.coffee#L28)), so I just went with 540px tall because that's what SWFs tend to be, and 100% wide because that keeps them in the centre by default. It'd be nice to have a better solution, but I don't, yet. I can't use 960x540 because that doesn't work unless I also add max-width: 100%, which fights with flexbox and other stuff. I can't do other things because of other similar issues. So, we just have to be extra careful about how we handle SWFs for the time being, until we manage to kill them off and we don't have to worry about this crap anymore. Oh.. but.. iframes are similar (intrinsic size doesn't match content size). F-💣.

**Comment by crystalrubik** [comment]
#1 helps a lot, thanks!

_Crystal Rubik_
Designer/Animator
CD Industrial Group Inc.
···································
crystal@cdiginc.com
1-866-628-3224
www.cdiginc.com

**Comment by ivyreese** [comment]
Glad to hear it!
