### ISSUE TITLE
Lost Connection?

### ISSUE THREAD

**Issue by iMcKelvie** [cdig/cd-module#18]
I have a note from the Trican meeting that Sean wanted to look into what would happen with a student's progress if their internet connection was interrupted. So, here's your reminder that you had questions about that, Sean!

**Comment by ivyreese** [comment]
I can tell you what should happen, in theory. This might help you verify behaviour.

Right now, we're [saving changes to SCORM after every change to the Scoring](https://github.com/cdig/cd-module/blob/master/dist/scripts/scoring.coffee#L145). There's no debouncing on this, so if a stream of points are awarded continuously, it'll attempt to save once per Scoring call, which could hypothetically happen multiple times per tick. This is not ideal because it's going to do _terrible things_ to the network, so there's a [log statement ("saving after awarding points")](https://github.com/cdig/cd-module/blob/master/dist/scripts/scoring.coffee#L144) to remind us that we _probably_ should change this behaviour before we ship. But the reason we're even doing this at all right now is because, if we don't save after each change, then we need to save on all possible exit conditions (back button in the browser, back button in the HUD, user types in a different URL, browser is quit, tab is closed — we need to test each of these, and any others, on every browser & device — and this strategy fails if the browser crashes). Previously, we didn't have hooks for saving at theses times, so I just defensively/naively saved after every score mutation. But, _I believe_ we now [have](https://github.com/cdig/cd-module/blob/master/dist/scripts/save-before-unload.coffee) [systems](https://github.com/cdig/cd-module/blob/master/dist/components/hud/menu-button.coffee#L15) in place that will cover all of these exit conditions (except crashing) — they're just un[der]tested. But ideally, it might be better to add one more hook for saving, which is a throttled/debounced save triggered after mutating data in KVStore. Basically like what we have now, but rate-limited to not thrash the network. Then we'll probably be covered even in the case of crashes.

Anyway, if the user loses the connection, then any calls to the SCORM API will fail in an undefined way, depending on the implementation of the SCORM API in the client LMS. Our systems will handle it just fine — if it fails silently, we're fine; if we get an errant response, we won't retry, and it will fail silently, and we're fine (this is all correct and desirable). When the user goes to leave the page (closing tab, back to launcher, whatever), it will attempt [a save with a popup to let the user know it is saving](https://github.com/cdig/cd-module/blob/master/dist/components/hud/menu-button.coffee#L15). If that save fails, it'll retry a save (invisibly) as the page is [unloading](https://github.com/cdig/cd-module/blob/master/dist/scripts/save-before-unload.coffee#L7) — this is likely blocking, but necessary. If that save fails, it'll [open a native popup window](https://github.com/cdig/cd-module/blob/master/dist/scripts/save-before-unload.coffee#L9) that blocks the closing of the page, warning the user that they have unsaved changes and if they leave the page that their data will be lost.

... I was very, very busy in January.

**Comment by ivyreese** [comment]
We're killing the current scoring codebase in prep for the new scoring infrastructure later this fall, so these concerns no longer apply.
