### ISSUE TITLE
Can we please have cd-activities stop at mains instead of pages?

### ISSUE THREAD

**Issue by crystalrubik** [cdig/cd-module#32]
Pretty please. 

I think having them stop at mains instead would help with some of the longer pages where we might have an activity within it and the user doesn't go too far past before being stopped.

Thanks!

**Comment by ivyreese** [comment]
Perhaps, locking should happen at each activity.

**Comment by crystalrubik** [comment]
Even better!

**Comment by iMcKelvie** [comment]
Seconding! And providing an example.

If you check out Hydraulic Fundamentals - Closed Loop Circuits, and scroll to Overload, you'll see an example of where a page had all of the activity tags removed, because it became too weird to stop someone at the bottom of a huge stack of main tags, and force them to go back several screens.

**Comment by ivyreese** [comment]
For now, I'm making the locking happen at `<cd-main>`s, just because there are some other complexities around how things get hidden that make it too difficult to go any more granular than this for the time being.
